version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: curl --fail http://localhost:5672
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  dashboard:
    build:
      context: ./apps/dashboard
      dockerfile: dockerfile
      target: dev
    container_name: dashboard
    restart: always
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      gateway-microservice:
        condition: service_healthy

  finder-microservice:
    build:
      context: ./apps/finder-microservice
      dockerfile: dockerfile
      target: dev
    container_name: finder-microservice
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      PORT: 3000
    depends_on:
      - rabbitmq

  gateway-microservice:
    build:
      context: ./apps/gateway-microservice
      dockerfile: dockerfile
      target: dev
    container_name: gateway-microservice
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      DATABASE_URL: postgresql://googieUser:googiePass@postgresDB:5432/googieDB?schema=public
    depends_on:
      - rabbitmq
    healthcheck:
      test: curl --fail http://localhost:3000
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "googieDB"
      POSTGRES_USER: "googieUser"
      POSTGRES_PASSWORD: "googiePass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - googieDB-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U googieUser -d googieDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres
      - default

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3005:3000

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  bull-metrics:
    container_name: bull-metrics
    image: igrek8/bullmq-prometheus:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROM_PREFIX=jobs
    ports:
      - 3009:3000
    depends_on:
      - redis

  postgres-metrics:
    container_name: postgres-metrics
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://googieUser:googiePass@postgresDB:5432/googieDB?sslmode=disable
    ports:
      - 9187:9187
    volumes:
      - ./postgres_exporter.yml:/bin/postgres_exporter.yml
    depends_on:
      - postgresDB

networks:
  default:
    name: my-network

  postgres:
    driver: bridge

volumes:
  googieDB-data:
  pgadmin-data:
