# Base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json ./

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
COPY . .
RUN pnpm install

# Build the NestJS app
RUN pnpm build

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD ["pnpm", "start:prod"]
