mutation CreateCampaign($createCampaignInput: CreateCampaignInput!) {
  createCampaign(createCampaignInput: $createCampaignInput) {
    endType
    keyword
    name
    providers
  }
}

mutation UpdateCampaign(
  $id: String!
  $updateCampaignInput: UpdateCampaignInput!
) {
  updateCampaign(id: $id, updateCampaignInput: $updateCampaignInput) {
    endType
    keyword
    name
    providers
  }
}

query Campaign($listCampaignInput: ListCampaignInput!) {
  campaign(ListCampaignInput: $listCampaignInput) {
    name
    keyword
    status
    providers
    endType
    endValue
    id
  }
}

query CampaignById($id: String!) {
  campaignById(id: $id) {
    name
    keyword
    status
    providers
    endType
    endValue
    id
  }
}
