apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: gateway-microservice:latest # You'll need to build and push this image
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: uri
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: url
