FROM node:18.14.2 as base

WORKDIR /app

COPY package*.json ./

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
COPY . .
RUN pnpm install

FROM base as dev

EXPOSE 3000 
EXPOSE 24678 

CMD [ "pnpm", "run", "dev" ]

FROM base as prod

# Build the NestJS app
RUN pnpm build

# Expose the port the app runs on
EXPOSE 3000

ENTRYPOINT ["node", ".output/server/index.mjs"]