# Base image
FROM node:18 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json ./

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
COPY . .
RUN pnpm --filter finder-microservice install

FROM builder AS dev

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD [ "pnpm", "--filter", "finder-microservice", "dev" ]

FROM builder AS prod
# Build the NestJS app
RUN pnpm --filter finder-microservice build

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD [ "pnpm", "--filter", "finder-microservice", "start:prod" ]
